import Footer from "@/components/Layouts/Footer/Footer";
import { Inter, Raleway, Space_Grotesk } from "next/font/google";
import Navbar from "../components/Layouts/NavBar/navbar";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--inter",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
});
const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} ${raleway.variable} ${inter.variable} bg-[#F5F8FF]`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
